[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
alpha_oracle = "BkQs8LxquVLUXHq44nQwpaenQzyZMBksrpVz2YN28MjV"

[programs.devnet]
alpha_oracle = "BkQs8LxquVLUXHq44nQwpaenQzyZMBksrpVz2YN28MjV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/jimmy-solana.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
